### ISSUE TITLE
Admin: add Public Suffix List panel

### ISSUE THREAD

**Issue by aral** [small-tech/basil#1]
The domain used for a Small Web Host must be on the [Public Suffix List](https://publicsuffix.org/) (PSL).

For public hosts (currently, those with payments types set to Token or Stripe), Basil will enforce this and not allow the set up of places otherwise for security reasons (cookies, etc.)

This is not a requirement for private hosts (payment type set to None).

## Tasks

  - [x] Add tab for PSL to admin.
  - [x] Add instructions in tab for how to add your domain to the public suffix list.
  - [x] Enforce inclusion in PSL for public hosts (private instances are exempt).

## References

  - [Public suffix list](https://publicsuffix.org/list/public_suffix_list.dat)
